# Generated by Django 3.0.4 on 2020-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date reported')),
                ('time', models.TimeField(verbose_name='time reported')),
            ],
            options={
                'verbose_name_plural': 'Incidences',
            },
        ),
    ]
