# Generated by Django 3.0.4 on 2020-05-02 20:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reporter', '0003_user_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Vis',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('car_driver', models.BooleanField(verbose_name='is a car driver')),
                ('visit_time', models.DateField(verbose_name='date of departure')),
            ],
            options={
                'verbose_name_plural': 'Users Visitors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user_res',
            options={'verbose_name_plural': 'Users Residents'},
        ),
    ]
