# Generated by Django 3.0.4 on 2020-05-02 21:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reporter', '0004_auto_20200502_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serv_Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('service', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_slug', models.SlugField(verbose_name='date of departure')),
            ],
            options={
                'verbose_name_plural': 'Service Managers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
