# Generated by Django 3.0.4 on 2020-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_serv_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serv_manager',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='serv_manager',
            name='service_slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('kind', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hazard', models.IntegerField(choices=[(1, 'Μικρή'), (2, 'Μεσαία'), (3, 'Μεγάλη')])),
                ('picture', models.ImageField(upload_to='', verbose_name='picture')),
                ('problem_slug', models.SlugField(max_length=200)),
                ('service', models.ManyToManyField(to='reporter.Serv_Manager')),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
    ]
