# Generated by Django 3.0.4 on 2020-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20200503_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture'),
        ),
    ]
