# Generated by Django 3.0.4 on 2020-05-03 23:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20200503_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_res',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
