# Generated by Django 3.0.4 on 2020-05-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('reporter', '0008_auto_20200504_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_res',
            options={'verbose_name_plural': 'Service Users'},
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='name',
        ),
        migrations.AddField(
            model_name='incidences',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incidences',
            name='incident_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='problem_kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.Problems'),
        ),
        migrations.AddField(
            model_name='incidences',
            name='status',
            field=models.CharField(choices=[('TR', 'Προς Εισαγωγή'), ('RE', 'Εισηγμένο'), ('TS', 'Προς Επίλυση'), ('SO', 'Λυμένο'), ('CA', 'Ακυρωμένο')], default='TR', max_length=2),
        ),
        migrations.AddField(
            model_name='incidences',
            name='support_indicator',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incidences',
            name='user_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.User_Res'),
        ),
        migrations.AddField(
            model_name='user_res',
            name='visit_time',
            field=models.DateField(null=True, verbose_name='date of departure'),
        ),
        migrations.AddField(
            model_name='user_res',
            name='visitor',
            field=models.BooleanField(null=True, verbose_name='is a visitor'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='car_driver',
            field=models.BooleanField(verbose_name='is a car driver'),
        ),
        migrations.DeleteModel(
            name='User_Vis',
        ),
    ]
