# Generated by Django 3.0.4 on 2020-05-08 20:14

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200507_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Χρήστη'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 23, 14, 19, 376740), verbose_name='Ημερομηνία Καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Τοποθεσία Προβλήματος'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='problem_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Problems', verbose_name='Είδος Προβλήματος'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('TR', 'Προς Εισαγωγή'), ('RE', 'Εισηγμένο'), ('TS', 'Προς Επίλυση'), ('SO', 'Λυμένο'), ('CA', 'Ακυρωμένο')], default='TR', max_length=2, verbose_name='Κατάσταση Προβλήματος'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='support_indicator',
            field=models.IntegerField(default=1, verbose_name='Δείκτης Συμπαράστασης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 8, 23, 14, 19, 376740), verbose_name='Ώρα Καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.User_Res', verbose_name='Όνομα Χρήστη'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='kind',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Είδος Προβλήματος'),
        ),
        migrations.AlterField(
            model_name='serv_manager',
            name='service',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Υπηρεσία'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Διεύθυνση Κατοικίας'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='car_driver',
            field=models.BooleanField(null=True, verbose_name='Είστε Οδηγός Αυτοκινήτου?'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='cellphone',
            field=models.CharField(max_length=10, verbose_name='Κινητό Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='visit_time',
            field=models.DateField(null=True, verbose_name='Ημερομηνία Αναχώρησης'),
        ),
        migrations.AlterField(
            model_name='user_res',
            name='visitor',
            field=models.BooleanField(null=True, verbose_name='Είστε Επισκέπτης στην Πόλη?'),
        ),
    ]
