# Generated by Django 3.0.4 on 2020-05-15 19:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_auto_20200513_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 22, 56, 10, 952688), verbose_name='Ημερομηνία Καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 15, 22, 56, 10, 952688), verbose_name='Ώρα Καταχώρησης'),
        ),
    ]
