# Generated by Django 3.0.4 on 2020-05-15 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0014_auto_20200515_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 23, 0, 38, 165044), verbose_name='Ημερομηνία Καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 15, 23, 0, 38, 165044), verbose_name='Ώρα Καταχώρησης'),
        ),
    ]
