# Generated by Django 3.0.4 on 2020-07-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0015_auto_20200515_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_res',
            options={'permissions': (('auth.change_user', 'auth.view_user'),), 'verbose_name_plural': 'Service Users'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 20, 52, 9, 231849), verbose_name='Ημερομηνία Καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 17, 20, 52, 9, 231849), verbose_name='Ώρα Καταχώρησης'),
        ),
    ]
